config/routes.rb
Feline::Application.routes.draw do
  devise_for :users

  resources :cats, :felines
  root :to => "home#index"

end

app/models/cat.rb
class Cat < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable,:confirmable and :activatable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
# before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :authenticate_user!, :except => [:index]
# GET /cats
  # GET /cats.xml
  def index
    @cats = Cat.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cats }
    end
  end

  # GET /cats/1
  # GET /cats/1.xml
  def show
    @cat = Cat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cat }
    end
  end

  # GET /cats/new
  # GET /cats/new.xml
  def new
    @cat = Cat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cat }
    end
  end

  # GET /cats/1/edit
  def edit
    @cat = Cat.find(params[:id])
  end

  # POST /cats
  # POST /cats.xml
  def create
    @cat = Cat.new(params[:cat])

    respond_to do |format|
      if @cat.save
        format.html { redirect_to(@cat, :notice => 'Cat was successfully created.') }
        format.xml  { render :xml => @cat, :status => :created, :location => @cat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cats/1
  # PUT /cats/1.xml
  def update
    @cat = Cat.find(params[:id])

    respond_to do |format|
      if @cat.update_attributes(params[:cat])
        format.html { redirect_to(@cat, :notice => 'Cat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.xml
  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy

    respond_to do |format|
      format.html { redirect_to(cats_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :img %><br />
    <%= f.text_field :img %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<h1>Listing cats</h1>

<table>
  <tr>
    <th>PIC </th>
    <th>Name</th>
    <th>Image </th>
    <th>Path</th>
    <th></th>
    <th></th>
  </tr>

<% @cats.reverse_each do |cat| %>
  <tr>
    <td><img src="<%= cat.img %>" height="50" width="50" /></td>
    <td><%= cat.name %></td>
    <td><%= cat.img %></td>
    <td><%= link_to 'Show', cat %></td>
    <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
    <td><%= link_to 'Destroy', cat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
   <img src="<%= @cat.img %>" height="100" width="100" /><br>
   <b>Name:</b>
   <%= @cat.name %>

   <b>Img:</b>
   <%= @cat.img %>
</p>


<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head> <title> <%= yield(:title) || "Untitled" %> 
 
       </title>
</head>
<body>
  <div id="container">
   <div id="user_nav">
     <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not You?
        <%= link_to "Sign out", destroy_user_session_path %>
     <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
     <% end %>
   </div>
<HR>
     <%= yield %>

  </div>  
</body>
</html>